import { SlashCommandBuilder, PermissionFlagsBits, ChannelType, ChatInputCommandInteraction, EmbedBuilder, TextChannel } from 'discord.js';
import ms from 'ms';
import { loadGiveaways, saveGiveaways, scheduleGiveaway, cancelGiveaway, endGiveaway, GiveawayData } from '../giveaway-utils';

export const data = new SlashCommandBuilder().setName('giveaway').setNameLocalization('ko','추첨').setDescription('Manage giveaways').setDescriptionLocalization('ko','추첨 이벤트를 관리합니다.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('start').setNameLocalization('ko','시작').setDescription('Start a giveaway').setDescriptionLocalization('ko','새로운 추첨을 시작합니다.').addStringOption(o=>o.setName('duration').setNameLocalization('ko','기간').setDescription('e.g. 1d 12h 30m').setDescriptionLocalization('ko','예: 1d 12h 30m').setRequired(true)).addIntegerOption(o=>o.setName('winners').setNameLocalization('ko','당첨자수').setDescription('Number of winners').setDescriptionLocalization('ko','당첨자 수').setRequired(true).setMinValue(1)).addStringOption(o=>o.setName('prize').setNameLocalization('ko','경품').setDescription('Prize').setDescriptionLocalization('ko','추첨 경품').setRequired(true)).addChannelOption(o=>o.setName('channel').setNameLocalization('ko','채널').setDescription('Giveaway channel').setDescriptionLocalization('ko','추첨 채널').addChannelTypes(ChannelType.GuildText).setRequired(false)))
.addSubcommand(s=>s.setName('reroll').setNameLocalization('ko','재추첨').setDescription('Reroll').setDescriptionLocalization('ko','당첨자를 다시 뽑습니다.').addStringOption(o=>o.setName('message-id').setNameLocalization('ko','메시지-id').setDescription('Giveaway message ID').setDescriptionLocalization('ko','추첨 메시지 ID').setRequired(true)))
.addSubcommand(s=>s.setName('end').setNameLocalization('ko','종료').setDescription('End early').setDescriptionLocalization('ko','추첨을 조기 종료합니다.').addStringOption(o=>o.setName('message-id').setNameLocalization('ko','메시지-id').setDescription('Giveaway message ID').setDescriptionLocalization('ko','추첨 메시지 ID').setRequired(true)));

export async function execute(i:ChatInputCommandInteraction){const sub=i.options.getSubcommand(); if(sub==='start')return start(i); if(sub==='reroll')return reroll(i); return end(i);}
async function start(i:ChatInputCommandInteraction){let duration=0; const s=i.options.getString('duration',true); try{for(const p of s.trim().split(/\s+/)){const n=ms(p);if(typeof n!=='number'||n<=0)throw 0;duration+=n;}}catch{return i.reply({content:'⚠️ 올바른 기간 형식입니다. 예: 1d 12h 30m',ephemeral:true});} const winners=i.options.getInteger('winners',true),prize=i.options.getString('prize',true),channel=(i.options.getChannel('channel') as TextChannel)||i.channel as TextChannel; if(!channel?.isTextBased())return i.reply({content:'텍스트 채널이 필요합니다.',ephemeral:true}); const end=Date.now()+duration; const msg=await channel.send({embeds:[new EmbedBuilder().setTitle('🎉 추첨 이벤트 🎉').setDescription(`**경품:** ${prize}`).addFields({name:'당첨자 수',value:`${winners}명`,inline:true},{name:'종료 시간',value:`<t:${Math.floor(end/1000)}:R>`,inline:true}).setColor(0x00FF00).setFooter({text:'🎉 반응을 눌러 참여하세요!'}).setTimestamp()]}); await msg.react('🎉'); const data:GiveawayData={messageId:msg.id,channelId:channel.id,guildId:i.guildId!,prize,winnerCount:winners,endTime:end,hostId:i.user.id,isActive:true}; const all=loadGiveaways();all.push(data);saveGiveaways(all);scheduleGiveaway(i.client,msg.id,end);return i.reply({content:`✅ 추첨이 시작되었습니다!\n메시지: ${msg.url}`,ephemeral:true});}
async function reroll(i:ChatInputCommandInteraction){const id=i.options.getString('message-id',true),all=loadGiveaways(),g=all.find(x=>x.messageId===id);if(!g)return i.reply({content:'⚠️ 해당 추첨을 찾을 수 없습니다.',ephemeral:true});if(g.isActive)return i.reply({content:'⚠️ 아직 종료되지 않은 추첨입니다.',ephemeral:true});const ch=await i.client.channels.fetch(g.channelId) as TextChannel;const msg=await ch.messages.fetch(g.messageId);const r=msg.reactions.cache.get('🎉');if(!r)return i.reply({content:'⚠️ 반응을 찾을 수 없습니다.',ephemeral:true});const existing=g.winners||[],users=await r.users.fetch(),p=users.filter(u=>!u.bot&&!existing.includes(u.id)).map(u=>u.id);if(!p.length)return i.reply({content:'⚠️ 재추첨할 참가자가 없습니다.',ephemeral:true});const w=p[Math.floor(Math.random()*p.length)];await ch.send({content:`🎉 재추첨 결과! 축하합니다 <@${w}> 님!\n**${g.prize}**에 당첨되셨습니다!`,reply:{messageReference:msg.id}});g.winners=[...existing,w];saveGiveaways(all);return i.reply({content:'✅ 재추첨이 완료되었습니다.',ephemeral:true});}
async function end(i:ChatInputCommandInteraction){const id=i.options.getString('message-id',true),g=loadGiveaways().find(x=>x.messageId===id);if(!g)return i.reply({content:'⚠️ 해당 추첨을 찾을 수 없습니다.',ephemeral:true});if(!g.isActive)return i.reply({content:'⚠️ 이미 종료된 추첨입니다.',ephemeral:true});cancelGiveaway(id);await endGiveaway(i.client,id);return i.reply({content:'✅ 추첨이 종료되었습니다.',ephemeral:true});}
